In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [2]:
def get_locality(soup):

    try:
        # Outer Tag Object
        locality = soup.find("span", attrs={"class":'component__pdPropAddress'}).text.strip().split()
        
        # Inner NavigatableString Object
        title_local = locality[-4][0:-1]

        # Title as a string value
        title_string = title_local.strip()

    except AttributeError:
        title_string = "N/A"

    return title_string

def get_region(soup):

    try:
        region = soup.find("span", attrs={"class":'component__pdPropAddress'}).text.strip().split()
        new_region=(region[-3]+' '+region[-2]).replace(',', '')
        
    except AttributeError:

        new_region = "N/A"

    return new_region

def get_price(soup):

    try:
        price = soup.find("span", attrs={"class":'component__pdPropValue'}).text.strip()
    
    except AttributeError:

        price = "N/A"	

    return price

def get_type(soup):
    try:
        house_type = soup.find("span", attrs={"class":'component__pdPropDetail2Heading'}).text.strip()
        new_type = house_type[0:4]
    except AttributeError:
        new_type = "N/A"	

    return new_type


def get_area(soup):
    try:
        area = soup.find("span", attrs={"id":'carpetArea_span'}).text

    except AttributeError:
        area = "N/A"	

    return area

In [3]:

if __name__ == '__main__':

    # user agent 
    HEADERS = ({'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36', 'Accept-Language': 'en-US, en;q=0.5'})

    # The webpage URL
    url='https://www.99acres.com/search/property/rent/navi-mumbai?city=15&preference=R&area_unit=1&res_com=R'

    # HTTP Request
    webpage=requests.get(url,headers=HEADERS)

    # Soup Object containing all data
    soup = BeautifulSoup(webpage.content, "html.parser")

    # Fetch links as List of Tag Objects
    links = soup.find_all("a", attrs={'body_med srpTuple__propertyName'})

    # Store the links
    links_list = []

    # Loop for extracting links from Tag Objects
    for link in links:
            links_list.append(link.get('href'))

    d = {"Locality":[], "Region":[],"price":[],"Apartment Type":[],"Area":[]}
    
    # Loop for extracting product details from each link 
    for link in links_list:
        new_webpage = requests.get(link, headers=HEADERS)

        new_soup = BeautifulSoup(new_webpage.content, "html.parser")

        # Function calls to display all necessary product information
        d['Locality'].append(get_locality(new_soup))
        d['Region'].append(get_region(new_soup))
        d['price'].append(get_price(new_soup))
        d['Apartment Type'].append(get_type(new_soup))
        d['Area'].append(get_area(new_soup))

    
    acre_df = pd.DataFrame.from_dict(d)
    acre_df['Locality'].replace('', np.nan, inplace=True)
    acre_df = acre_df.dropna(subset=['Locality'])
    acre_df.to_csv("acre_data.csv", header=True, index=False)

In [4]:
acre_df.head(50)

         Locality       Region     price Apartment Type  Area
0        Kharghar  Navi Mumbai    16,000           1BHK   N/A
1        Kharghar  Navi Mumbai    20,000           1BHK   342
2           Vashi  Navi Mumbai    61,000           3BHK  1100
3        Kharghar  Navi Mumbai    56,500           3BHK  1250
4           Vashi  Navi Mumbai    80,000           3BHK  1000
5   Koperkhairane  Navi Mumbai    40,000           2BHK   N/A
6        Seawoods  Navi Mumbai    65,000           2BHK   900
7         Sanpada  Navi Mumbai    55,000           2BHK  1200
8        Ghansoli  Navi Mumbai    52,222           2BHK   638
9          Panvel  Navi Mumbai    15,000           2BHK   453
10         Nevali  Navi Mumbai      7000           1BHK   450
11         Panvel  Navi Mumbai    32,000           3BHK   920
12         Panvel  Navi Mumbai    25,500           2BHK   720
13          Vashi  Navi Mumbai    38,000           2Bed   N/A
14        Kamothe  Navi Mumbai    13,000           1BHK   390
15         Panvel  Navi Mumbai    31,000           3BHK  1264
16         Panvel  Navi Mumbai    20,000           2BHK  1100
17       Ghansoli  Navi Mumbai    42,000           2BHK   750
18          Vashi  Navi Mumbai  2.25 Lac           5Bed   N/A
19          Vashi  Navi Mumbai    45,000           2BHK   750
20  Koperkhairane  Navi Mumbai    75,000           3BHK  8869
21       Khairane  Navi Mumbai    40,000           2BHK   700
22       Ghansoli  Navi Mumbai    45,000           2BHK   710
23       Ghansoli  Navi Mumbai    45,000           2BHK   700
24       Kharghar  Navi Mumbai    35,000           2BHK   650
25         Airoli  Navi Mumbai    70,000           3BHK   952
26          Beach  Navi Mumbai    90,000           3BHK   N/A

{'Locality': ['Kharghar',
  'Kharghar',
  'Vashi',
  'Kharghar',
  'Vashi',
  'Koperkhairane',
  'Seawoods',
  'Sanpada',
  'Ghansoli',
  'Panvel',
  'Nevali',
  'Panvel',
  'Panvel',
  'Vashi',
  'Kamothe',
  'Panvel',
  'Panvel',
  'Ghansoli',
  'Vashi',
  'Vashi',
  'Koperkhairane',
  'Khairane',
  'Ghansoli',
  'Ghansoli',
  'Kharghar',
  'Airoli',
  'Beach'],
 'Region': ['Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai',
  'Navi Mumbai'],
 'price': ['16,000',
  '20,000',
  '61,000',
  '56,500',
  '80,000',
  '40,000',
  '65,000',
  '55,000',
  '52,222',
  '15,000',
  '7000',
  '32,000',
  '25,500',
  '38,000',
  '13,000',
  '31,000',
  '20,000',
  '42,000',
  '2.25 Lac',
  '45,000',
  '75,000',
  '40,000',
  '45,000',
  '45,000',
  '35,000',
  '70,000',
  '90,000'],
 'Apartment Type': ['1BHK',
  '1BHK',
  '3BHK',
  '3BHK',
  '3BHK',
  '2BHK',
  '2BHK',
  '2BHK',
  '2BHK',
  '2BHK',
  '1BHK',
  '3BHK',
  '2BHK',
  '2Bed',
  '1BHK',
  '3BHK',
  '2BHK',
  '2BHK',
  '5Bed',
  '2BHK',
  '3BHK',
  '2BHK',
  '2BHK',
  '2BHK',
  '2BHK',
  '3BHK',
  '3BHK'],
 'Area': ['N/A',
  '342',
  '1100',
  '1250',
  '1000',
  'N/A',
  '900',
  '1200',
  '638',
  '453',
  '450',
  '920',
  '720',
  'N/A',
  '390',
  '1264',
  '1100',
  '750',
  'N/A',
  '750',
  '8869',
  '700',
  '710',
  '700',
  '650',
  '952',
  'N/A']}